
### Get all characters
GET http://0.0.0.0:8080/characters HTTP/1.1

### Get a single character
GET http://0.0.0.0:8080/characters/1 HTTP/1.1

### Create a character
POST http://0.0.0.0:8080/characters HTTP/1.1
Content-Type: application/json

{
  "name": "Saren Arterius",
  "species": 3,
  "gender": 1,
  "class": "Rogue Spectre"
}